import { HolidaysType } from '../types/types';

export const holidays: HolidaysType[] = [
  {
    date: 14,
    month: 1,
    year: 2023,
    reason: 'Makara Sankranti',
  },
  {
    date: 26,
    month: 1,
    year: 2023,
    reason: 'Republic Day',
  },
  {
    date: 18,
    month: 2,
    year: 2023,
    reason: 'Maha Shivaratri',
  },
  {
    date: 22,
    month: 3,
    year: 2023,
    reason: 'Ugadi',
  },
  {
    date: 4,
    month: 4,
    year: 2023,
    reason: 'Mahavir Jayanti',
  },
  {
    date: 7,
    month: 4,
    year: 2023,
    reason: 'Good Friday',
  },
  {
    date: 14,
    month: 4,
    year: 2023,
    reason: 'Dr Ambedkar Jayanti',
  },
  {
    date: 22,
    month: 4,
    year: 2023,
    reason: 'Idul Fitr',
  },
  {
    date: 23,
    month: 4,
    year: 2023,
    reason: 'Basava Jayanti',
  },
  {
    date: 1,
    month: 5,
    year: 2023,
    reason: 'May Day',
  },
  {
    date: 29,
    month: 6,
    year: 2023,
    reason: 'Bakrid / Eid al Adha',
  },
  {
    date: 29,
    month: 7,
    year: 2023,
    reason: 'Muharram',
  },
  {
    date: 15,
    month: 8,
    year: 2023,
    reason: 'Independence Day',
  },
  {
    date: 19,
    month: 9,
    year: 2023,
    reason: 'Ganesh Chaturthi',
  },
  {
    date: 28,
    month: 9,
    year: 2023,
    reason: 'Eid e Milad',
  },
  {
    date: 2,
    month: 10,
    year: 2023,
    reason: 'Gandhi Jayanti',
  },
  {
    date: 14,
    month: 10,
    year: 2023,
    reason: 'Mahalaya Amavasye',
  },
  {
    date: 23,
    month: 10,
    year: 2023,
    reason: 'Maha Navami',
  },
  {
    date: 24,
    month: 10,
    year: 2023,
    reason: 'Vijaya Dashami',
  },
  {
    date: 28,
    month: 10,
    year: 2023,
    reason: 'Maharishi Valmiki Jayanti',
  },
  {
    date: 1,
    month: 11,
    year: 2023,
    reason: 'Kannada Rajyothsava',
  },
  {
    date: 12,
    month: 11,
    year: 2023,
    reason: 'Deepavali',
  },
  {
    date: 13,
    month: 11,
    year: 2023,
    reason: 'Deepavali Holiday',
  },
  {
    date: 30,
    month: 11,
    year: 2023,
    reason: 'Kanakadasa Jayanti',
  },
  {
    date: 25,
    month: 12,
    year: 2023,
    reason: 'Christmas Day',
  },
];
